dsumaroka\spring-boot-intro
dsumaroka/spring-boot-intro pull request #1
Opened 2024-09-11 13:33 UTC by dsumaroka

2024-09-11 14:00 UTC, Elena-Bruyako requested changes
see comments

2024-09-11 14:00 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/model/Book.java
> +@Table(name = "book")
```suggestion
@Getter
@Setter
@Table(name = "books")
```

2024-09-11 14:00 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/model/Book.java
> +    }
redundant constructors
in main use setters

2024-09-11 14:00 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/repository/impl/BookRepositoryImpl.java
> +@Repository
```suggestion
@Repository
@RequiredArgsConstructor
```

2024-09-11 14:00 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/repository/impl/BookRepositoryImpl.java
> +    }
```suggestion
```

2024-09-11 14:00 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/repository/impl/BookRepositoryImpl.java
> +            throw new RuntimeException("Can't insert into DB" + book);
```suggestion
            throw new DataProcessingException("Can't insert into DB" + book);
```

2024-09-11 14:00 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/repository/impl/BookRepositoryImpl.java
> +            throw new RuntimeException("Can't get all books from DB", e);
```suggestion
            throw new DataProcessingException("Can't get all books from DB", e);
```

2024-09-11 14:00 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/service/impl/BookServiceImpl.java
> +@Service
```suggestion
@Service
@RequiredArgsConstructor
```

2024-09-11 14:00 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/service/impl/BookServiceImpl.java
> +    private BookRepository bookRepository;
```suggestion
    private final BookRepository bookRepository;
```

2024-09-11 14:09 UTC, dsumaroka commented
Ок

Ср, 11 сент. 2024 г. в 17:01, Olena Bruiako ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> see comments
> ------------------------------
>
> In src/main/java/mate/academy/springbootintro/model/Book.java
> <https://github.com/dsumaroka/spring-boot-intro/pull/1#discussion_r1754644510>
> :
>
> > ***@***.***
> ***@***.***(name = "book")
>
> ⬇️ Suggested change
>
> ***@***.***
> ***@***.***(name = "book")
> ***@***.***
> ***@***.***
> ***@***.***(name = "books")
>
> ------------------------------
>
> In src/main/java/mate/academy/springbootintro/model/Book.java
> <https://github.com/dsumaroka/spring-boot-intro/pull/1#discussion_r1754647948>
> :
>
> > +    private Book() {
> +    }
> +
> +    public ***@***.*** String title, @NonNull String author,
> +                @NonNull String isbn, @NonNull BigDecimal price) {
> +        this.title = title;
> +        this.author = author;
> +        this.isbn = isbn;
> +        this.price = price;
> +    }
>
> redundant constructors
> in main use setters
> ------------------------------
>
> In
> src/main/java/mate/academy/springbootintro/repository/impl/BookRepositoryImpl.java
> <https://github.com/dsumaroka/spring-boot-intro/pull/1#discussion_r1754648550>
> :
>
> > @@ -0,0 +1,51 @@
> +package mate.academy.springbootintro.repository.impl;
> +
> +import java.util.List;
> +import mate.academy.springbootintro.model.Book;
> +import mate.academy.springbootintro.repository.BookRepository;
> +import org.hibernate.Session;
> +import org.hibernate.SessionFactory;
> +import org.hibernate.Transaction;
> +import org.springframework.beans.factory.annotation.Autowired;
> +import org.springframework.stereotype.Repository;
> +
> ***@***.***
>
> ⬇️ Suggested change
>
> ***@***.***
> ***@***.***
> ***@***.***
>
> ------------------------------
>
> In
> src/main/java/mate/academy/springbootintro/repository/impl/BookRepositoryImpl.java
> <https://github.com/dsumaroka/spring-boot-intro/pull/1#discussion_r1754648917>
> :
>
> > +
> +    @Autowired
> +    public BookRepositoryImpl(SessionFactory sessionFactory) {
> +        this.sessionFactory = sessionFactory;
> +    }
>
> ⬇️ Suggested change
>
> -
> -    @Autowired
> -    public BookRepositoryImpl(SessionFactory sessionFactory) {
> -        this.sessionFactory = sessionFactory;
> -    }
>
> ------------------------------
>
> In
> src/main/java/mate/academy/springbootintro/repository/impl/BookRepositoryImpl.java
> <https://github.com/dsumaroka/spring-boot-intro/pull/1#discussion_r1754649659>
> :
>
> > +
> +    @Override
> +    public Book save(Book book) {
> +        Session session = null;
> +        Transaction transaction = null;
> +        try {
> +            session = sessionFactory.openSession();
> +            transaction = session.beginTransaction();
> +            session.persist(book);
> +            transaction.commit();
> +            return book;
> +        } catch (Exception e) {
> +            if (transaction != null) {
> +                transaction.rollback();
> +            }
> +            throw new RuntimeException("Can't insert into DB" + book);
>
> ⬇️ Suggested change
>
> -            throw new RuntimeException("Can't insert into DB" + book);
> +            throw new DataProcessingException("Can't insert into DB" + book);
>
> ------------------------------
>
> In
> src/main/java/mate/academy/springbootintro/repository/impl/BookRepositoryImpl.java
> <https://github.com/dsumaroka/spring-boot-intro/pull/1#discussion_r1754649957>
> :
>
> > +                transaction.rollback();
> +            }
> +            throw new RuntimeException("Can't insert into DB" + book);
> +        } finally {
> +            if (session != null) {
> +                session.close();
> +            }
> +        }
> +    }
> +
> +    @Override
> +    public List<Book> findAll() {
> +        try (Session session = sessionFactory.openSession()) {
> +            return session.createQuery("FROM Book", Book.class).getResultList();
> +        } catch (Exception e) {
> +            throw new RuntimeException("Can't get all books from DB", e);
>
> ⬇️ Suggested change
>
> -            throw new RuntimeException("Can't get all books from DB", e);
> +            throw new DataProcessingException("Can't get all books from DB", e);
>
> ------------------------------
>
> In
> src/main/java/mate/academy/springbootintro/service/impl/BookServiceImpl.java
> <https://github.com/dsumaroka/spring-boot-intro/pull/1#discussion_r1754650700>
> :
>
> > @@ -0,0 +1,24 @@
> +package mate.academy.springbootintro.service.impl;
> +
> +import java.util.List;
> +import mate.academy.springbootintro.model.Book;
> +import mate.academy.springbootintro.repository.BookRepository;
> +import mate.academy.springbootintro.service.BookService;
> +import org.springframework.beans.factory.annotation.Autowired;
> +import org.springframework.stereotype.Service;
> +
> ***@***.***
>
> ⬇️ Suggested change
>
> ***@***.***
> ***@***.***
> ***@***.***
>
> ------------------------------
>
> In
> src/main/java/mate/academy/springbootintro/service/impl/BookServiceImpl.java
> <https://github.com/dsumaroka/spring-boot-intro/pull/1#discussion_r1754653061>
> :
>
> > +    @Autowired
> +    private BookRepository bookRepository;
>
> ⬇️ Suggested change
>
> -    @Autowired
> -    private BookRepository bookRepository;
> +    private final BookRepository bookRepository;
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dsumaroka/spring-boot-intro/pull/1#pullrequestreview-2297175530>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A7UEH4GDWLSCLQVNW4WFWYDZWBELFAVCNFSM6AAAAABOA7VVH6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEOJXGE3TKNJTGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-09-12 12:02 UTC, Elena-Bruyako requested changes
see comments

2024-09-12 12:02 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/model/Book.java
> +@Entity
```suggestion
@Entity
@Getter
@Setter
```

2024-09-12 12:02 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/model/Book.java
> +    public Book() {
remove

2024-09-12 12:02 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/model/Book.java
> +    public Long getId() {
remove getters and setters

2024-09-12 12:02 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/model/Book.java
> +    public String toString() {
remove

2024-09-12 12:23 UTC, Elena-Bruyako approved these changes
In next HW remove mate from package name

2024-09-12 12:44 UTC, dsumaroka commented
Ок. Thanks

Чт, 12 сент. 2024 г. в 15:24, Olena Bruiako ***@***.***>:

> ***@***.**** approved this pull request.
>
> In next HW remove mate from package name
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dsumaroka/spring-boot-intro/pull/1#pullrequestreview-2300144705>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A7UEH4BAPZ4GK75M5SC4HC3ZWGBWLAVCNFSM6AAAAABOA7VVH6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGMBQGE2DINZQGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-09-12 13:53 UTC, merged