dsumaroka/spring-boot-intro-web
dsumaroka/spring-boot-intro pull request #2
Opened 2024-09-21 14:13 UTC by dsumaroka

2024-09-22 17:41 UTC, Elena-Bruyako requested changes
see comments

2024-09-22 17:41 UTC, Elena-Bruyako commented on pom.xml
> +			<version>1.5.5.Final</version>
```suggestion
			<version>${mapstruct.version}</version>
```
create property

2024-09-22 17:41 UTC, Elena-Bruyako commented on pom.xml
> +			<version>1.5.5.Final</version>
same

2024-09-22 17:41 UTC, Elena-Bruyako commented on src/main/java/springboot/web/example/repository/impl/BookRepositoryImpl.java
> +        }
add catch block

2024-09-22 17:41 UTC, Elena-Bruyako commented on src/main/java/springboot/web/example/service/impl/BookServiceImpl.java
> +        return bookRepositoryAll.stream()
```suggestion
        return bookRepository.findAll().stream()
```

2024-09-22 17:52 UTC, dsumaroka commented
Ок

Вс, 22 сент. 2024 г. в 20:41, Olena Bruiako ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> see comments
> ------------------------------
>
> In pom.xml
> <https://github.com/dsumaroka/spring-boot-intro/pull/2#discussion_r1770601013>
> :
>
> >  		</dependency>
>  		<dependency>
>  			<groupId>org.springframework.boot</groupId>
>  			<artifactId>spring-boot-starter-test</artifactId>
>  			<scope>test</scope>
>  		</dependency>
> -	</dependencies>
> +		<dependency>
> +			<groupId>org.springframework.boot</groupId>
> +			<artifactId>spring-boot-starter-web</artifactId>
> +		</dependency>
> +		<dependency>
> +			<groupId>org.mapstruct</groupId>
> +			<artifactId>mapstruct</artifactId>
> +			<version>1.5.5.Final</version>
>
> ⬇️ Suggested change
>
> -			<version>1.5.5.Final</version>
> +			<version>${mapstruct.version}</version>
>
> create property
> ------------------------------
>
> In pom.xml
> <https://github.com/dsumaroka/spring-boot-intro/pull/2#discussion_r1770601037>
> :
>
> >  		</dependency>
>  		<dependency>
>  			<groupId>org.springframework.boot</groupId>
>  			<artifactId>spring-boot-starter-test</artifactId>
>  			<scope>test</scope>
>  		</dependency>
> -	</dependencies>
> +		<dependency>
> +			<groupId>org.springframework.boot</groupId>
> +			<artifactId>spring-boot-starter-web</artifactId>
> +		</dependency>
> +		<dependency>
> +			<groupId>org.mapstruct</groupId>
> +			<artifactId>mapstruct</artifactId>
> +			<version>1.5.5.Final</version>
> +		</dependency>
> +		<!-- MapStruct Annotation Processor -->
> +		<dependency>
> +			<groupId>org.mapstruct</groupId>
> +			<artifactId>mapstruct-processor</artifactId>
> +			<version>1.5.5.Final</version>
>
> same
> ------------------------------
>
> In
> src/main/java/springboot/web/example/repository/impl/BookRepositoryImpl.java
> <https://github.com/dsumaroka/spring-boot-intro/pull/2#discussion_r1770601299>
> :
>
> > @@ -45,4 +46,12 @@ public List<Book> findAll() {
>              throw new DataProcessingException("Can't get all books from DB", e);
>          }
>      }
> +
> +    @Override
> +    public Optional<Book> findById(Long id) {
> +        try (Session session = sessionFactory.openSession()) {
> +            Book book = session.find(Book.class, id);
> +            return Optional.ofNullable(book);
> +        }
>
> add catch block
> ------------------------------
>
> In src/main/java/springboot/web/example/service/impl/BookServiceImpl.java
> <https://github.com/dsumaroka/spring-boot-intro/pull/2#discussion_r1770601385>
> :
>
> > +        List<Book> bookRepositoryAll = bookRepository.findAll();
> +        return bookRepositoryAll.stream()
>
> ⬇️ Suggested change
>
> -        List<Book> bookRepositoryAll = bookRepository.findAll();
> -        return bookRepositoryAll.stream()
> +        return bookRepository.findAll().stream()
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dsumaroka/spring-boot-intro/pull/2#pullrequestreview-2320894709>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A7UEH4EPPTHKYFC4BTIGUW3ZX36OLAVCNFSM6AAAAABOTUB4T6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGMRQHA4TINZQHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-09-23 12:38 UTC, Elena-Bruyako requested changes
minor comments

2024-09-23 12:38 UTC, Elena-Bruyako commented on pom.xml
> +							<version>1.5.5.Final</version>
get from property

2024-09-23 12:38 UTC, Elena-Bruyako commented on src/main/java/springboot/web/example/exceptions/DataProcessingException.java
> +package springboot.web.example.exceptions;
```suggestion
package springboot.web.example.exception;
```

2024-09-23 12:46 UTC, dsumaroka commented
Ok

пн, 23 сент. 2024 г. в 15:38, Olena Bruiako ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> minor comments
> ------------------------------
>
> In pom.xml
> <https://github.com/dsumaroka/spring-boot-intro/pull/2#discussion_r1771322079>
> :
>
> > +					<source>17</source>
> +					<target>17</target>
> +					<compilerArgs>
> +						<arg>--add-opens</arg>
> +						<arg>jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED</arg>
> +					</compilerArgs>
> +					<annotationProcessorPaths>
> +						<path>
> +							<groupId>org.projectlombok</groupId>
> +							<artifactId>lombok</artifactId>
> +							<version>1.18.34</version>
> +						</path>
> +						<path>
> +							<groupId>org.mapstruct</groupId>
> +							<artifactId>mapstruct-processor</artifactId>
> +							<version>1.5.5.Final</version>
>
> get from property
> ------------------------------
>
> In
> src/main/java/springboot/web/example/exceptions/DataProcessingException.java
> <https://github.com/dsumaroka/spring-boot-intro/pull/2#discussion_r1771323142>
> :
>
> > @@ -1,4 +1,4 @@
> -package mate.academy.springbootintro.exceptions;
> +package springboot.web.example.exceptions;
>
> ⬇️ Suggested change
>
> -package springboot.web.example.exceptions;
> +package springboot.web.example.exception;
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dsumaroka/spring-boot-intro/pull/2#pullrequestreview-2322056300>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A7UEH4FXZCLHHNRK5KGKDH3ZYADVTAVCNFSM6AAAAABOTUB4T6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGMRSGA2TMMZQGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-09-23 13:15 UTC, Elena-Bruyako approved these changes

2024-09-23 13:23 UTC, merged